export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAIL = "SEARCH_MOVIES_FAIL";
export const ISLOADING_MOVIES = "ISLOADING_MOVIES";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_FAIL = "GET_DETAILS_FAIL";
export const ISLOADING_DETAIL = "ISLOADING_DETAIL";
export const ISMODAL_SHOW = "ISMODAL_SHOW";
